spring.application.name=projecte3
# MongoDB
spring.mongodb.uri=mongodb://root:example@localhost:27017/projecte3_db?authSource=admin
spring.mongodb.database=projecte3_db
logging.level.org.springframework.data.mongodb=DEBUG